version: '3'

services:
  app:
    build: .
    command: "npm run start:dev"
    # depends_on:
    #   - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app:delegated

  # postgres:
  #   container_name: 'postgres-node'
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
